# Generated by Django 4.2.4 on 2023-08-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proff', models.CharField(max_length=255, verbose_name='Job title')),
                ('location', models.CharField(max_length=55, verbose_name='Location')),
                ('jobtime', models.CharField(choices=[('Full_time', 'Full_time'), ('Part_time', 'Part_time')], max_length=50, verbose_name='Job Time')),
                ('min_salary', models.IntegerField(verbose_name='Min salary')),
                ('max_salary', models.IntegerField(verbose_name='Max salary')),
                ('dt', models.DateField(auto_now_add=True)),
                ('Img', models.ImageField(upload_to='Jobs_media', verbose_name='Imagers')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
