# Generated by Django 4.2.4 on 2023-08-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_joblist_jobtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='jobtime',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50, verbose_name='Job Time'),
        ),
    ]
