# Generated by Django 4.2.4 on 2023-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_img_joblist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='categories',
            field=models.CharField(blank=True, choices=[('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Human Resource', 'Human Resource'), ('Project Management', 'Project Management'), ('Business Development', 'Business Development'), ('Sales & Communication', 'Sales & Communication'), ('Teaching & Education', 'Teaching & Education'), ('Design & Creative', 'Design & Creative')], max_length=50, verbose_name='Category'),
        ),
    ]
