# Generated by Django 4.2.4 on 2023-08-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_joblist_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proff', models.CharField(max_length=255, verbose_name='Job title')),
                ('location', models.CharField(max_length=55, verbose_name='Location')),
                ('jobtime', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50, verbose_name='Job Time')),
                ('min_salary', models.IntegerField(verbose_name='Min salary')),
                ('max_salary', models.IntegerField(verbose_name='Max salary')),
                ('dt', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='Jobs_media', verbose_name='Imagers')),
                ('categories', models.CharField(blank=True, choices=[('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Human Resource', 'Human Resource'), ('Project Management', 'Project Management'), ('Business Development', 'Business Development'), ('Sales & Communication', 'Sales & Communication'), ('Teaching & Education', 'Teaching & Education'), ('Design & Creative', 'Design & Creative')], max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Job Create',
                'verbose_name_plural': 'Job Create',
            },
        ),
    ]
