# Generated by Django 4.2.4 on 2023-08-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_jobcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcreate',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Job description'),
        ),
        migrations.AddField(
            model_name='jobcreate',
            name='qualifications',
            field=models.TextField(blank=True, verbose_name='Qualifications'),
        ),
        migrations.AddField(
            model_name='jobcreate',
            name='responsibility',
            field=models.TextField(blank=True, verbose_name='Responsibility'),
        ),
    ]
