# Generated by Django 4.2.4 on 2023-08-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_jobcreate_about_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('portfolio', models.CharField(max_length=100, verbose_name='Portfolio')),
                ('coverlatter', models.TextField(verbose_name='Coverlatter')),
                ('img', models.ImageField(upload_to='Apply_media', verbose_name='Imagers')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobcreate')),
            ],
            options={
                'verbose_name': 'Apply',
                'verbose_name_plural': 'Apply',
            },
        ),
    ]
