# Generated by Django 4.2.4 on 2023-08-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCleints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Cleint_media', verbose_name='Imagers')),
                ('text', models.TextField(verbose_name='Text')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('prof', models.CharField(max_length=50, verbose_name='Profession')),
            ],
            options={
                'verbose_name': 'Cleint',
                'verbose_name_plural': 'Cleints',
            },
        ),
    ]
