# Generated by Django 4.2.4 on 2023-08-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_maincategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImgers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Imagers')),
            ],
        ),
    ]
