# Generated by Django 4.2.4 on 2023-08-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_aboutimgers_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutImgers',
        ),
    ]
