# Generated by Django 4.2.4 on 2023-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_aboutimgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeabout',
            name='skill',
            field=models.TextField(blank=True, verbose_name='skill'),
        ),
    ]
