# Generated by Django 4.2.4 on 2023-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_homeabout_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('img', models.ImageField(upload_to='Cleint_media', verbose_name='Imagers')),
                ('prof', models.CharField(max_length=255, verbose_name='Profession')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
