# Generated by Django 4.2.4 on 2023-08-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Talent_media', verbose_name='imagers')),
                ('prof', models.CharField(max_length=255, verbose_name='profession')),
                ('jobtime', models.CharField(max_length=55, verbose_name='Job Time')),
                ('rank', models.CharField(choices=[('Junior', 'Junior'), ('Middel', 'Middel'), ('Senior', 'Senior'), ('Leader', 'Leader')], max_length=55, verbose_name='rank')),
                ('address', models.CharField(max_length=255, verbose_name='Addres')),
                ('coverlatter', models.TextField(verbose_name='Coverlatter')),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
            },
        ),
    ]
