# Generated by Django 4.2.4 on 2023-08-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='name',
            field=models.CharField(default=0, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
