# Generated by Django 4.2.4 on 2023-08-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_talent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='skill',
            field=models.TextField(null=True, verbose_name='skills'),
        ),
        migrations.AddField(
            model_name='talent',
            name='summery',
            field=models.TextField(null=True, verbose_name='summery'),
        ),
    ]
