# Generated by Django 4.2.4 on 2023-08-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_messagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
