# Generated by Django 4.2.4 on 2023-08-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_contactus_options_alter_messagemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeabout',
            options={'verbose_name': 'Home-about', 'verbose_name_plural': 'Home-about'},
        ),
        migrations.AlterModelOptions(
            name='maincategories',
            options={'verbose_name': 'Main Category', 'verbose_name_plural': 'Main Categories'},
        ),
    ]
