# Generated by Django 4.2.4 on 2023-08-22 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0028_alter_homeabout_options_alter_maincategories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcreate',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcreate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcreate_likes', to='main.jobcreate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
