# Generated by Django 4.2.4 on 2023-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_jobcreate_likes_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobList',
        ),
        migrations.DeleteModel(
            name='OurCleints',
        ),
        migrations.AlterField(
            model_name='jobcreate',
            name='categories',
            field=models.CharField(blank=True, choices=[('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Human_Resource', 'Human Resource'), ('Project_Management', 'Project Management'), ('Business_Development', 'Business Development'), ('Sales_and_Communication', 'Sales & Communication'), ('Teaching_and_Education', 'Teaching & Education'), ('Design_and_Creative', 'Design & Creative')], max_length=50, verbose_name='Category'),
        ),
    ]
