# Generated by Django 4.2.4 on 2023-08-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_delete_joblist_delete_ourcleints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='phone'),
        ),
    ]
