# Generated by Django 4.2.4 on 2023-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Open to work'),
        ),
    ]
