# Generated by Django 4.2.4 on 2023-09-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_userinfo_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcreate',
            name='categories',
            field=models.CharField(blank=True, choices=[('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Human Resource', 'Human Resource'), ('Project Management', 'Project Management'), ('Business Development', 'Business Development'), ('Sales_and Communication', 'Sales & Communication'), ('Teaching and Education', 'Teaching & Education'), ('Design and Creative', 'Design & Creative')], max_length=50, verbose_name='Category'),
        ),
    ]
