# Generated by Django 4.2.4 on 2023-09-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_jobcreate_savec_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcreate',
            name='dissave',
            field=models.BooleanField(default=False),
        ),
    ]
