# Generated by Django 4.2.4 on 2023-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_jobcreate_dissave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcreate',
            name='dissave',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jobcreate',
            name='savec',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
