# Generated by Django 4.2.4 on 2023-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_jobcreate_dissave_alter_jobcreate_savec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcreate',
            name='dissave',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
