# Generated by Django 4.2.4 on 2023-12-02 11:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_jobcreate_dissave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='apply',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None, verbose_name='Phoen number'),
            preserve_default=False,
        ),
    ]
