# Generated by Django 4.2.4 on 2023-12-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_homeabout_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcreate',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
