# Generated by Django 4.2.4 on 2023-12-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_jobcreate_points_userinfo_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='resi',
            field=models.FileField(null=True, upload_to='resiumes', verbose_name='Resiume'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='img',
            field=models.ImageField(blank=True, upload_to='Apply_media', verbose_name='Imagers'),
        ),
    ]
