# Generated by Django 4.2.4 on 2023-12-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_apply_resi_alter_apply_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='register_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
