# Generated by Django 4.2.1 on 2023-06-02 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product name')),
                ('price', models.PositiveIntegerField(verbose_name='Product price')),
                ('img', models.ImageField(upload_to='index_images', verbose_name='Product image')),
                ('logo', models.ImageField(upload_to='index_images', verbose_name='Product image logo')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Product create date')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_prod', to='main.sub_category')),
            ],
        ),
    ]
