# Generated by Django 4.2.1 on 2023-06-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='contact_name',
        ),
    ]
